name: record_result
description: record_result is a Dart package that provides a type called Result for handling the outcomes of operations. It can represent either a successful result or a failure, allowing you to handle errors in a more functional and expressive way.
version: 1.0.0+1

repository: https://github.com/albinson-arias/record_result

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  equatable: ^2.0.5
