name: record_result
description: record_result is a package that provides a type called Result for handling the outcomes of operations.
version: 1.0.1+2

repository: https://github.com/albinson-arias/record_result

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  equatable: ^2.0.5
